language: node_js
node_js:
  - "16"


edge: true

branches:
  only:
    - main


stages:
  - name: build
 # - name: deploy


notifications:
  email:
    recipients:
      - maynoldemar@gmail.com
    on_success: always
    on_failure: always 


cache:
  directories:
    - "node_modules"


jobs:
  include:
    - stage: build
      install:
        - echo "Installing dependencies"
        - npm install
      script:
        - echo "Building the project"
        - npm run build
      after_script:
        - echo "after_script script phase"
        #- npm run generate-report

    # - stage: deploy
    #   before_deploy:
    #     - echo "Deploying the project"
    #   script:
    #     - echo "script_deploy phase"
    #     - npm install
    #     - npm run build
    #     - npx prisma migrate deploy
    #     - npx prisma generate
    #     - echo la clave es $HEROKU_API_KEY
      #deploy: 
       # provider: heroku
        #edge: true
        #api_key: $HEROKU_API_KEY
        #app: coomuvemar-backend
        #on:
         # branch: main
